### ISSUE TITLE
I feel so close, but there are still some things I'm not sure how to fix. 

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/dsn1674-assignment-7#1]
1. The gradient on the main banner I can't figure out how to get the dark transparency gradient fading into the image. I almost wanted to just change it in Photoshop, then re-save it into the website. 
2. The beetles up top. I can make it so there's 1 at the top left, and I can make them repeat across the top. Is there a way to just repeat twice? 
3. If I could just figure out how to put the buttons on top of the images, it would solve multiple issues on the bottom. I tried putting position: absolute on the button and position: relative on the images, but they didn't react the same way as with the figure and figcaption. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
_Number 1:_

For the transparent colour in the gradient, just write `transparent` or use `rgba()`:
https://github.com/algonquindesign/html-css/tree/gh-pages/using-css#rgb-semi-transparency

---

_Number 2:_

You can't just repeat twice; you need to specify the beetle twice in the list.

---

_Number 3:_

You're right with `absolute` and `relative` but `relative` must go onto a parent element of the button, so the `<div class="unit">`.

**Comment by DizzyDez** [comment]
Is there a problem with my beetle .svg up top? I thought I had to just have the it blown up as large as possible as an .ai file, but Now I'm second guessing as to if it was the right size.

**Comment by thomasjbradley** [comment]
Blowing up the beetle in Illustrator is a good idea, really big, like 256 px or more.
Then use CSS to shrink it back down to the size you want.

**Comment by DizzyDez** [comment]
I saw from your link that my banner should have been a background image instead of placed with the image tag. but when I went to place it with url, the image does not show up. What did I do wrong?

**Comment by thomasjbradley** [comment]
It's just that `linear-gradient` needs a dash in it:
https://github.com/DizzyDez/dsn1674-assignment-7/blob/gh-pages/css/main.css#L71
